version: '3.1'
services:
  nginx:
    tty: true
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: always
    ports:
        - '80:80'
        - '443:443'
    expose:
        - '80'
        - '443'
  linebot:
    container_name: linebot
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.linebot
    ports:
      - "8000:8000"
    expose:
      - "8000"
  