FROM nginx:latest

RUN apt update

RUN cd /usr/share/nginx/html && mkdir .well-known

RUN cd /usr/share/nginx/html/.well-known && mkdir pki-validation

# 1. 처음 실행
# COPY default.conf /etc/nginx/conf.d/default_first.conf 

# 2. 두번째 실행
COPY default.conf /etc/nginx/conf.d/default.conf

COPY ./ssl/linebot.pem /etc/nginx/linebot.pem

COPY ./ssl/linebot.key /etc/nginx/linebot.key

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]